ci: troubleshoot ci issues
Signed-off-by: Artsiom Koltun <artsiom.koltun@intel.com>

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -9,7 +9,52 @@ on:
   pull_request:
     branches: [ main ]
 
+permissions:
+  contents: read
+
 jobs:
-  call:
-    uses: opiproject/actions/.github/workflows/docker-publish.yml@main
-    secrets: inherit
+  test:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: docker/setup-qemu-action@v3
+      - uses: docker/setup-buildx-action@v3.0.0
+      - name: Install Docker Compose v2.36.0
+        run: |
+          mkdir -p ~/.docker/cli-plugins/
+          curl -SL https://github.com/docker/compose/releases/download/v2.36.0/docker-compose-linux-$(uname -m) -o ~/.docker/cli-plugins/docker-compose
+          chmod +x ~/.docker/cli-plugins/docker-compose
+          docker compose version
+
+      - name: Install additional kernel modules needed for OPI like VRF
+        run: sudo apt-get install linux-modules-extra-$(uname -r)
+
+      - name: Load additional kernel modules needed for OPI like VRF
+        run: sudo modprobe -v vrf
+
+      - name: Debug
+        run: |
+          set -x
+          echo "Done"
+        # docker compose build opi-mangoboost-server
+      - name: Start containers
+        run: docker compose up --build --force-recreate --detach opi-test
+
+      - name: Run Tests
+        run: |
+          set -x
+          name=$(docker compose ps | grep opi-test | awk '{print $1}')
+          rc=$(docker wait "${name}")
+          if [ "${rc}" != "0" ]; then
+              echo "opi-test failed:"
+              docker logs "${name}"
+              exit 1
+          fi
+
+      - name: Logs
+        if: always()
+        run: docker compose logs
+
+      - name: Stop containers
+        if: always()
+        run: docker compose down --volumes --remove-orphans
